version: '2'
services:
    marksense-app:
        image: marksense
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://marksense-postgresql:5432/markSense
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    marksense-postgresql:
        extends:
            file: postgresql.yml
            service: marksense-postgresql
