version: '2'
services:
    marksense-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/markSense/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=markSense
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
